[arcene]
doc_id = '1cnuQwVtQ-FsJ_En9_ln2KU0n30wJ4ffe'

[covertype]
doc_id = '1ixC-jAgdAgPnCL37uaTEnBep7q43liNP'

[higgs]
doc_id = '1mz6E-5eV5ThnzdbimvTTeTTGSoJTjS_I'

[poker]
doc_id = '1yVdp4pHSmrFasHhX4j4vtxVHYHUvciun'

[sarcos]
doc_id = '1Nr7MIWogLo0aY_uQdSCSfGysMr5Wswq5'
