name: Publish the Python Package to PyPI (and Test PyPI)

on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project files
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install python build tools
        run: |
          python -m pip install build --user
      - name: Build package distributions
        working-directory: python/
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: python/dist/
