name: Package Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Load Cached Python Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('./python/setup.py') }}-${{ hashFiles('./python/tests/requirements.txt') }}
      - name: Install Python Package & Dependencies
        working-directory: ./python/
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r python/tests/requirements.txt -e .
      - name: Run Tests
        run: pytest
