name: Python Package Tests

on:
  push:
    branches:
      - main
    paths:
      - 'python/**'
      - '!**/*.md'
  pull_request:
    branches:
      - main
    paths:
      - 'python/**'
      - '!**/*.md'
  workflow_dispatch:

jobs:
  test-with-datasets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Load Cached Python Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('./python/setup.py') }}-${{ hashFiles('./python/tests/requirements.txt') }}
      - name: Install Python Package & Dependencies
        working-directory: python/
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r tests/requirements.txt -e .
      - name: Run Tests
        working-directory: python/
        run: pytest -m "not large and dataset"
  test-without-datasets:
    strategy:
      matrix:
        python_version: ['3.8', '3.9']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}
      - name: Load Cached Python Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('./python/setup.py') }}-${{ hashFiles('./python/tests/requirements.txt') }}
      - name: Install Python Package & Dependencies
        working-directory: python/
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r tests/requirements.txt -e .
      - name: Run Tests
        working-directory: python/
        run: pytest -m "not dataset"
